name: 버그 리포트
description: 발견한 버그를 신고해주세요
title: "[Bug] "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: 🐛 버그 설명
      placeholder: ex) 로그인 시 500 에러 발생

  - type: textarea
    attributes:
      label: ⚠️ 재현 방법
      placeholder: |
        1. 로그인 페이지 진입
        2. 카카오 로그인 클릭
        3. 에러 발생

  - type: textarea
    attributes:
      label: 🖥 실행 환경
      placeholder: ex) MacOS, Chrome 115, Postman

  - type: input
    attributes:
      label: 📄 관련 로그/스크린샷
      placeholder: (옵션) URL 또는 파일 첨부

  - type: textarea
    attributes:
      label: ✅ 예상 동작
      placeholder: ex) 로그인 성공 후 /home으로 리다이렉트
