name: 기타 요청 사항
description: 위 템플릿에 해당되지 않는 작업 요청
title: "[Task] "
labels: ["task"]

body:
  - type: textarea
    attributes:
      label: 작업 설명
      placeholder: 자유롭게 작성해주세요.

  - type: textarea
    attributes:
      label: 관련 내용 or 참고 링크
      placeholder: ex) 노션, Figma, 이슈 #24 등
