name: 작업 요청
description: 문서 작성, 리팩토링, 설정 변경 등의 요청
title: "[Chore] "
labels: ["chore", "refactor"]

body:
  - type: textarea
    attributes:
      label: 📝 작업 내용
      placeholder: ex) dotenv 설정 구조 변경

  - type: textarea
    attributes:
      label: 🗂 관련 파일
      placeholder: ex) config/env.js

  - type: textarea
    attributes:
      label: 🧱 작업 목적 / 필요성
      placeholder: ex) 개발환경과 배포환경 구분을 명확히 하기 위해

  - type: textarea
    attributes:
      label: 📌 기타 참고 사항
      placeholder: 추가 설명 필요 시 작성
