name: Deploy LOOPy-BE to EC2

on:
  push:
    branches:
      - icebread
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for Prisma changes
        uses: dorny/paths-filter@v3
        id: prisma-changes
        with:
          filters: |
            prisma: ["prisma/**"]

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host loopy-server
            HostName ${{ secrets.EC2_HOST }}
            User ubuntu
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END

      - name: Copy project files to EC2
        run: |
          ssh loopy-server 'sudo mkdir -p /opt/loopy-be'
          ssh loopy-server 'sudo chown ubuntu:ubuntu /opt/loopy-be'
          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '.env' \
            --exclude '*.log' \
            ./ loopy-server:/opt/loopy-be/

      - name: Deploy with Docker
        run: |
          ssh loopy-server '
            cd /opt/loopy-be
            
            echo "Stopping current containers..."
            docker stop loopy-app || true
            docker rm loopy-app || true
            docker rmi loopy-be || true
            docker system prune -f || true
            
            echo "Building new image..."
            docker build -t loopy-be .
            
            echo "Starting new container..."
            docker run -d -p 3000:3000 --name loopy-app --env-file .env loopy-be
            
            echo "Waiting for container to start..."
            sleep 15
            
            echo "Checking container status..."
            docker ps
            
            echo "Checking recent logs..."
            docker logs loopy-app --tail=30
          '

      - name: Prisma Migration
        if: steps.prisma-changes.outputs.prisma == 'true'
        run: |
          ssh loopy-server '
            cd /opt/loopy-be
            echo "Applying Prisma migrations..."
            docker exec loopy-app pnpm exec prisma migrate deploy
          '

      - name: Health Check
        run: |
          ssh loopy-server '
            echo "Starting health check..."
            
            sleep 10
            
            if docker ps | grep -q loopy-app; then
              echo "Container is running successfully."
              
              for i in {1..5}; do
                if curl -f -s http://localhost:3000 > /dev/null 2>&1; then
                  echo "Server is responding normally!"
                  echo "LOOPy-BE deployment completed successfully!"
                  exit 0
                fi
                echo "Health check retry... ($i/5)"
                sleep 10
              done
              
              echo "Server is not responding yet but container is running."
              echo "Please wait a little more."
            else
              echo "Container execution failed!"
              echo "Error logs:"
              docker logs loopy-app
              exit 1
            fi
          '

      - name: Deployment Summary
        if: always()
        run: |
          echo "Deployment Summary"
          echo "- Project: LOOPy-BE"
          echo "- Branch: ${{ github.ref_name }}"
          echo "- Server: ${{ secrets.EC2_HOST }}"
          echo "- Time: $(date '+%Y-%m-%d %H:%M:%S')"
