name: Deploy LOOPy-BE to EC2

on:
  push:
    branches:
      - icebread
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host loopy-server
            HostName ${{ secrets.EC2_HOST }}
            User ubuntu
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END

      - name: Update code and deploy
        run: |
          ssh loopy-server '
            cd /opt/loopy-be
            
            echo "Pulling latest code..."
            git pull origin icebread
            
            echo "Stopping current container..."
            docker stop loopy-app || true
            docker rm loopy-app || true
            
            echo "Building new image with latest code..."
            docker build -t loopy-be .
            
            echo "Starting new container..."
            docker run -d -p 3000:3000 --name loopy-app --env-file .env loopy-be
            
            echo "Waiting for container to start..."
            sleep 15
            
            echo "Checking container status..."
            docker ps
            
            echo "Checking recent logs..."
            docker logs loopy-app --tail=20
          '

      - name: Health Check
        run: |
          ssh loopy-server '
            echo "Starting health check..."
            
            for i in {1..6}; do
              if curl -f -s http://localhost:3000 > /dev/null 2>&1; then
                echo "Server is responding normally!"
                echo "Deployment completed successfully!"
                exit 0
              fi
              echo "Health check retry... ($i/6)"
              sleep 10
            done
            
            echo "Health check failed. Checking logs..."
            docker logs loopy-app --tail=50
            exit 1
          '

      - name: Deployment Summary
        if: always()
        run: |
          echo "Deployment Summary"
          echo "- Project: LOOPy-BE"
          echo "- Branch: ${{ github.ref_name }}"
          echo "- Server: ${{ secrets.EC2_HOST }}"
          echo "- Time: $(date '+%Y-%m-%d %H:%M:%S')"
